version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: builder
    image: go_auth:1.0.0
    volumes:
      - ./api:/go/src/app
    depends_on:
      - postgres
      - redis
    env_file:
      - ./api/.env
    environment:
      PORT: :3001
    ports:
      - "3001:3001"
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"

  # web:
  #   image: web:1.0.0
  #   build:
  #     dockerfile: api/Dockerfile
  #     context: ./web/.
  #   volumes:
  #     - ./app/node_modules
  #     - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - api
  #   environment:
  #     PORT: 3000
  #   ports:
  #     - 3000:3000

  postgres:
    image: postgres:12.10-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: go_db
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:6.2.7-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data


volumes:
  database:
  redis:
